version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sircilla_db
    restart: always
    environment:
      POSTGRES_USER: sircilla_admin
      POSTGRES_PASSWORD: sircilla_secure_pass
      POSTGRES_DB: sircilla_workers
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
